version: '3'

networks:
  db-net:
    driver: host
    external: true

services:
  dataflow-server:
    user: root
    image: localhost:5000/spring-cloud-dataflow-server:local
    networks:
      - db-net
    container_name: dataflow-server
    ports:
      - "9393:9393"
    extra_hosts:
      - "ubuntu:192.168.239.132"
      - "host.docker.internal:host-gateway"
    restart: always
    privileged: true
    #external_links:
    #  - mysql
    volumes:
      - "/home/afshin/docker/repository/scdf/tmp:/tmp"
      - "/home/afshin/docker/repository/scdf/workspace:/workspace"
    environment:
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
      - JDK_JAVA_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://afshin:3306/dataflow?permitMysqlScheme&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME='admin'
      - SPRING_DATASOURCE_PASSWORD='123456'
      - spring.cloud.dataflow.features.streams-enabled=false\
      - spring.cloud.dataflow.features.schedules-enabled=false\
      - spring.cloud.dataflow.features.tasks-enabled=true\
      #- spring.config.additional-location=/workspace/maven.yaml
    #entrypoint: "./wait-for-it.sh mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -jar /spring-cloud-skipper-server.jar"